# Generated by Django 5.0 on 2024-01-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_rename_categoria_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='imagen',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
    ]
